### ISSUE TITLE
Optimize for valid routes rather than missing ones

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_router#27]
Right now, Fragments are stored in nested hash: https://github.com/luckyframework/lucky_router/blob/8b66bbd490b8629474b20f5bd4cce4a82d559b7d/src/lucky_router/matcher.cr#L51

The keys for this hash are meant to avoid searching for a fragment unless necessary. There are two checks before it searches the fragments:
1. That there is a fragment that handles a given http method.
2. That there is a fragment that handles a given number of path segments.

I propose that we remove these checks because they actually slow down what I assume will be the more common case, a valid request to an app. My tests are showing that the router is ~15% faster at handling valid routes when this nested hash is removed.

My thoughts are that instead of having this hash in the matcher, there would just be a root fragment. All new routes would be added to it and all requests would be searched with it. It would represent the root path. Then, inside each fragment, instead of having one payload, it would have a hash that maps a request method to a payload. This check will always be necessary but we move it to only when we have found a matching path.

This change would slow down finding unhandled requests but, as I said above, I believe that optimizing for the "happy path" is more beneficial.

**Comment by paulcsmith** [comment]
@matthewmcgarvey The original reason for checking the size of the route was to make the router more reliable. The other radix implementations would sometimes have issues because it would go down a tree path and then would fail because it was missing the last part or something. And it didn't go back up a level to check for another match.

So I think it needs to check the size at first to maintain that reliability. But if there is a way to still have the reliability *and* the speed then that's great too.

Here is a specific case I can think of:

`/posts/:id`
`/posts/:id/edit`

If the first route happens to be the first one added then the tree would match the first part, match the second part, then fail because the third part is empty. What it should do is never have tried the first route because it would never match. A similar problem happens with HTTP methods, where you have similar paths, but under a different HTTP method.

I think this is necessary to make the router as reliable as it is and work for routes added in an arbitrary order, but happy to chat about this more

**Comment by matthewmcgarvey** [comment]
@paulcsmith I'm having trouble seeing where removing the path size check would cause problems in this case. Are there specs in place to test what you're thinking of or could we add them?

**Comment by paulcsmith** [comment]
@matthewmcgarvey I believe the specs should cover these cases :D So if you wanna give it a go then that's a-ok! I may just be misunderstanding how it'd work, so if it is faster and covers all the edge-cases covered in the specs it should be good to go👍
