### ISSUE TITLE
LuckyRouter::Matcher(T)#duplicate_check should reveal more information

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky_router#44]
LuckyRouter::Matcher(T)#duplicate_check says that there _is_ a duplicate route, but doesn't say anything about the route that was already defined. One would expect that the action it points to is known, and this would give the user a clue. Of course, this error prevents `lucky routes` from printing the route table.

**Comment by matthewmcgarvey** [comment]
One of the issues with printing the duplicate and the existing route is that we don't store that existing route as it was entered, it was normalized and could be different. I think we just update the storage to be a hash or something so that we can do the lookup with the normalized route but get the original.

**Comment by BrucePerens** [comment]
@matthewmcgarvey I find the information printed by `lucky routes` to be adequate, wouldn't this also come from normalized data?

**Comment by matthewmcgarvey** [comment]
I believe Lucky stores routes in it's own data structure outside of LuckyRouter. The "normalized" routes was only just added for the duplicate checks. It could be an opportunity to remove that duplication, though.
